name: ifa_21312060
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

